FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
# Expose the Vite host so it's accessible outside the Docker container
CMD ["npm", "run", "dev", "--", "--host"]
