server {
    listen 80;
    server_name localhost;

    # Serve static React assets
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Handle React Router SPA fallback
        try_files $uri $uri/ /index.html;
    }
}
